# Generated by Django 3.2.12 on 2022-03-29 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique_for_date='publish_at')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='articles/imgs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('article_subject', models.CharField(choices=[('politic', 'Political article'), ('economic', 'Economic article'), ('auto', 'Article about auto'), ('realty', 'Realty article')], default='politic', max_length=42)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
